# Generated by Django 3.2.8 on 2022-02-21 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='name')),
                ('image', models.ImageField(blank=True, upload_to='champions')),
                ('price_rp', models.PositiveBigIntegerField(verbose_name='price rp')),
                ('price_be', models.PositiveBigIntegerField(verbose_name='price blue essence')),
                ('role', models.CharField(max_length=16, verbose_name='role')),
                ('role_b', models.CharField(blank=True, max_length=16, verbose_name='second role')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='name')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='loot image')),
            ],
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='name')),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='name')),
                ('image', models.ImageField(blank=True, upload_to='skins')),
                ('price_rp', models.PositiveBigIntegerField(verbose_name='price_rp')),
                ('division', models.CharField(blank=True, max_length=16, verbose_name='division')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.collectioncategory', verbose_name='category')),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.champion', verbose_name='champion')),
            ],
        ),
        migrations.AddField(
            model_name='champion',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.collectioncategory', verbose_name='category'),
        ),
    ]
