# Generated by Django 3.2.8 on 2022-03-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='blue_essence',
            field=models.PositiveIntegerField(default=0, verbose_name='blue essence balance'),
        ),
        migrations.AlterField(
            model_name='player',
            name='rp',
            field=models.PositiveIntegerField(default=0, verbose_name='rp balance'),
        ),
    ]
