# Generated by Django 4.0.4 on 2022-05-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lootapp', '0002_material_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedmaterial',
            name='opened',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
