# Generated by Django 3.2.8 on 2022-02-23 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lootapp', '0002_material_quantity'),
        ('orderapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='material',
            field=models.ForeignKey(limit_choices_to=models.Q(('is_purchasable', True)), on_delete=django.db.models.deletion.CASCADE, to='lootapp.material', verbose_name='Material'),
        ),
    ]
